version: '3.8'

services:
  web:
    build: .
    command: gunicorn algomania.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Exposing the Redis port for visibility (optional)

  celery:
    build: .
    command: celery -A algomania worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0  # Correct URL for Celery

  beat:
    build: .
    command: celery -A algomania beat --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0  # Correct URL for Beat

networks:
  default:
    driver: bridge
