# Generated by Django 5.0.7 on 2024-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_submission_user_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('titleSlug', models.SlugField(max_length=255, unique=True)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
