# Generated by Django 5.0.7 on 2024-08-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teacherquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(choices=[('PROF', 'Professor'), ('NML', 'Normal'), ('CONT', 'Contest'), ('POTD', 'Problem of the day')], max_length=10),
        ),
    ]
