# Generated by Django 5.0.7 on 2024-08-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PROF', 'Professor'), ('STUD', 'Student')], default='STUD', max_length=50),
        ),
    ]
